# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vikram/Desktop/C/Acalc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vikram/Desktop/C/Acalc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vikram/Desktop/C/Acalc/CMakeFiles /home/vikram/Desktop/C/Acalc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vikram/Desktop/C/Acalc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named acalc

# Build rule for target.
acalc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acalc
.PHONY : acalc

# fast build rule for target.
acalc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/build
.PHONY : acalc/fast

src/ast.o: src/ast.c.o
.PHONY : src/ast.o

# target to build an object file
src/ast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/ast.c.o
.PHONY : src/ast.c.o

src/ast.i: src/ast.c.i
.PHONY : src/ast.i

# target to preprocess a source file
src/ast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/ast.c.i
.PHONY : src/ast.c.i

src/ast.s: src/ast.c.s
.PHONY : src/ast.s

# target to generate assembly for a file
src/ast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/ast.c.s
.PHONY : src/ast.c.s

src/astPrinter.o: src/astPrinter.c.o
.PHONY : src/astPrinter.o

# target to build an object file
src/astPrinter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/astPrinter.c.o
.PHONY : src/astPrinter.c.o

src/astPrinter.i: src/astPrinter.c.i
.PHONY : src/astPrinter.i

# target to preprocess a source file
src/astPrinter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/astPrinter.c.i
.PHONY : src/astPrinter.c.i

src/astPrinter.s: src/astPrinter.c.s
.PHONY : src/astPrinter.s

# target to generate assembly for a file
src/astPrinter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/astPrinter.c.s
.PHONY : src/astPrinter.c.s

src/environment.o: src/environment.c.o
.PHONY : src/environment.o

# target to build an object file
src/environment.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/environment.c.o
.PHONY : src/environment.c.o

src/environment.i: src/environment.c.i
.PHONY : src/environment.i

# target to preprocess a source file
src/environment.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/environment.c.i
.PHONY : src/environment.c.i

src/environment.s: src/environment.c.s
.PHONY : src/environment.s

# target to generate assembly for a file
src/environment.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/environment.c.s
.PHONY : src/environment.c.s

src/error.o: src/error.c.o
.PHONY : src/error.o

# target to build an object file
src/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/error.c.o
.PHONY : src/error.c.o

src/error.i: src/error.c.i
.PHONY : src/error.i

# target to preprocess a source file
src/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/error.c.i
.PHONY : src/error.c.i

src/error.s: src/error.c.s
.PHONY : src/error.s

# target to generate assembly for a file
src/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/error.c.s
.PHONY : src/error.c.s

src/expr.o: src/expr.c.o
.PHONY : src/expr.o

# target to build an object file
src/expr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/expr.c.o
.PHONY : src/expr.c.o

src/expr.i: src/expr.c.i
.PHONY : src/expr.i

# target to preprocess a source file
src/expr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/expr.c.i
.PHONY : src/expr.c.i

src/expr.s: src/expr.c.s
.PHONY : src/expr.s

# target to generate assembly for a file
src/expr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/expr.c.s
.PHONY : src/expr.c.s

src/interpreter.o: src/interpreter.c.o
.PHONY : src/interpreter.o

# target to build an object file
src/interpreter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/interpreter.c.o
.PHONY : src/interpreter.c.o

src/interpreter.i: src/interpreter.c.i
.PHONY : src/interpreter.i

# target to preprocess a source file
src/interpreter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/interpreter.c.i
.PHONY : src/interpreter.c.i

src/interpreter.s: src/interpreter.c.s
.PHONY : src/interpreter.s

# target to generate assembly for a file
src/interpreter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/interpreter.c.s
.PHONY : src/interpreter.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/main.c.s
.PHONY : src/main.c.s

src/parser.o: src/parser.c.o
.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/parser.c.s
.PHONY : src/parser.c.s

src/scanner.o: src/scanner.c.o
.PHONY : src/scanner.o

# target to build an object file
src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/scanner.c.o
.PHONY : src/scanner.c.o

src/scanner.i: src/scanner.c.i
.PHONY : src/scanner.i

# target to preprocess a source file
src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/scanner.c.i
.PHONY : src/scanner.c.i

src/scanner.s: src/scanner.c.s
.PHONY : src/scanner.s

# target to generate assembly for a file
src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/scanner.c.s
.PHONY : src/scanner.c.s

src/vector.o: src/vector.c.o
.PHONY : src/vector.o

# target to build an object file
src/vector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/vector.c.o
.PHONY : src/vector.c.o

src/vector.i: src/vector.c.i
.PHONY : src/vector.i

# target to preprocess a source file
src/vector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/vector.c.i
.PHONY : src/vector.c.i

src/vector.s: src/vector.c.s
.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acalc.dir/build.make CMakeFiles/acalc.dir/src/vector.c.s
.PHONY : src/vector.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... acalc"
	@echo "... src/ast.o"
	@echo "... src/ast.i"
	@echo "... src/ast.s"
	@echo "... src/astPrinter.o"
	@echo "... src/astPrinter.i"
	@echo "... src/astPrinter.s"
	@echo "... src/environment.o"
	@echo "... src/environment.i"
	@echo "... src/environment.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/expr.o"
	@echo "... src/expr.i"
	@echo "... src/expr.s"
	@echo "... src/interpreter.o"
	@echo "... src/interpreter.i"
	@echo "... src/interpreter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/scanner.o"
	@echo "... src/scanner.i"
	@echo "... src/scanner.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

